config/routes.rb
Rails.application.routes.draw do
  root to: "cocktails#index"
  resources :cocktails, only: [:index, :show, :new, :create, :destroy] do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_one_attached :photo
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true

  def to_label
    name.capitalize
  end
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, presence: true
  validates :ingredient, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }

  def to_label
    name.capitalize
  end
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @path = ''
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to root_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file%>
  <%= f.submit "Add", class: "btn btn-primary" %>
<% end %>

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/3323682/pexels-photo-3323682.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940);">
  <div class="container">
    <h1>Cocktails</h1>
  </div>
</div>

<div class="container">
  <div class="cards">
    <% @cocktails.each do |cocktail| %>
      <% if cocktail.photo.attached? %>
        <% @path = cocktail.photo.key %>
      <% else %>
        <% @path = "a-cup-filled-of-green-tea-with-lemon-3677150_lftutq" %>
      <% end %>

      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url( <%= cl_image_path @path, height: 400, width: 400, crop: :fill %> )">
        <p><%= link_to cocktail.name, cocktail_path(cocktail) %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <h1>Add a New Cocktail</h1>
  <%= render 'cocktails/form' %>
</div>

app/views/cocktails/show.html.erb
<div class="container">
  <div class="card-product">

    <% if @cocktail.photo.attached? %>
      <% @path = @cocktail.photo.key %>
    <% else %>
      <% @path = "a-cup-filled-of-green-tea-with-lemon-3677150_lftutq" %>
    <% end %>

    <%= cl_image_tag @path, height: 400, width: 400, crop: :fill %>

    <div class="card-product-infos">
      <h1><%= @cocktail.name %></h1>
      <div class="d-flex justify-content-between">
        <% @cocktail.doses.each do |dose| %>
          <div class="list-item text-left">
            <p><%= dose.description %> | <%= dose.ingredient.name %></p>
            <button id="sweet-alert-demo" class="btn btn-sm btn-light">Delete</button>
            <%= link_to "", dose_path(dose), method: :delete, class: 'hidden', id: "delete-link" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="card-product-actions">
    <%= link_to "Back", cocktails_path, class: 'btn btn-primary' %>
    <%= link_to "Add a New Dose", new_cocktail_dose_path(@cocktail), class: 'btn btn-primary' %>
    <button id="sweet-alert-demo" class="btn btn-primary">Delete Cocktail</button>
    <%= link_to "", cocktail_path(@cocktail), method: :delete, class: 'hidden', id: "delete-link"%>
  </div>
</div>

app/views/doses/_form.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient, collection: Ingredient.order(:name)%>
  <%= f.submit "Add", class: 'btn btn-primary'%>
<% end %>

app/views/doses/new.html.erb
<div class="container">
  <h1>Add a New Dose</h1>
  <%= render 'doses/form' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cocktails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_pack_tag 'application' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <%= link_to cocktails_path, class: "navbar-brand" do %>
        <i class="fas fa-cocktail"></i>
      <% end %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li>
            <%= link_to "Add New Cocktail", new_cocktail_path, class: "btn btn-primary" %>
          </li>
        </ul>
      </div>
    </div>

    <div class="footer">
      <div class="footer-links">
        <a href="https://github.com/yukaitozu/"><i class="fab fa-github"></i></a>
        <a href="https://www.linkedin.com/in/yukaitozu/"><i class="fab fa-linkedin"></i></a>
      </div>
      <div class="footer-copyright">
        ©Yuka Itozu
      </div>
    </div>

    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>